### ISSUE TITLE
configure: error: "could not find headers for libxml2:

### ISSUE THREAD

**Issue by Sarge2013** [mysqludf/lib_mysqludf_xml#1]
Hello,
installing on CentOS 6.4 I met the following problem
./configure
it starts configuration but stops with
checking for libxml2... configure: error: "could not find headers for libxml2: /usr/include/libxml or /usr/include/libxml2/libxml"

On http://stackoverflow.com/questions/5544074/cannot-compile-when-using-libxml I found an advise
"You need always to keep the -I/usr/include/libxml2 in your gcc statement, so that it can find the header files"

But how to use it, what file and how should be corrected ?
Or may be there is another solution ?
Thank you very much in advance !

**Comment by jasny** [comment]
You need to install the libxml2 development files. If you're on Debian or Ubuntu run `sudo apt-get install libxml2-dev`.  On CentOS run `yum install libxml2-devel`.

**Comment by Sarge2013** [comment]
I already tried
yum install libxml2-devel
Loaded plugins: priorities
176 packages excluded due to repository priority protections
Setting up Install Process
Package libxml2-devel-2.7.6-12.el6_4.1.x86_64 already installed and latest version
Nothing to do

So I already have latest package of libxml2-devel  - but it does not solve the problem.
Best regards,
Serge

**Comment by jasny** [comment]
Hmm try running `./configure --with-libxml2=/usr/bin/xml2-config`

**Comment by Sarge2013** [comment]
I have same again

[root@zulu281 xmlmaster]# ./configure --with-libxml2=/usr/bin/xml2-config
.........................
configure: setting libdir to mysql plugin dir /usr/lib64/mysql/plugin
checking for libxml2... configure: error: "could not find libxml2: /usr/bin/xml2-config/lib/libxml2.so"
[root@zulu281 xmlmaster]#

I do not insist but may be a solution from StackOverflow (see above) could be useful ?
I just don't know how to use it...

Monday, August 5, 2013, 1:27:26 AM, you wrote:

Hmm try running ./configure --with-libxml2=/usr/bin/xml2-config

**Comment by jasny** [comment]
The StackOverflow solution is about compiling libxml2. You should use the one build by CentOS. So that answer isn't appropriate.

You should have the executable '/usr/bin/xml2-config', which is in package [libxml2-devel-2.7.6-12.el6_4.1.x86_64](http://pkgs.org/centos-6-rhel-6/centos-rhel-updates-x86_64/libxml2-devel-2.7.6-12.el6_4.1.x86_64.rpm.html). However the configure script is not recognizing it as an executable.

Please check if that file exists using `which xml2-config`. If is doesn't exists, it means something went wrong installing the libxml2-devel package. In that case I can't help you further.

**Comment by Sarge2013** [comment]
Good morning !
I did
[root@zulu281 ~]# find / -name xml2-config
/usr/bin/xml2-config

So the file exists - please, see the one attached - I replied by email.

May be inside the file there are non-expected paths to other files/libraries what needs for your installation ?

If attachment is not here - may I send you directly to your email ?

Best regards
Serge

Monday, August 5, 2013, 1:47:45 AM, you wrote:

The StackOverflow solution is about compiling libxml2. You should use the one build by CentOS. So that answer isn't appropriate.
You should have the executable '/usr/bin/xml2-config', which is in package libxml2-devel-2.7.6-12.el6_4.1.x86_64. However the configure script is not recognizing it as an executable.
Please check if that file exists using which xml2-config. If is doesn't exists, it means something went wrong installing the libxml2-devel package. In that case I can't help you further.

**Comment by Sarge2013** [comment]
Dear Arnold, good morning again!

Is it also yours https://github.com/mysqludf/lib_mysqludf_preg ?

Because this package was installed without a problem.
So we can suppose there is something in lib_mysqludf_preg what is not in lib_mysqludf_xml

**Comment by jasny** [comment]
It's not mine, but also from the repo. It doesn't use libxml2 though.

I'll have to look into it later.

**Comment by Sarge2013** [comment]
Dear Arnold, you can close the issue  :) in my case it was a bug or mess inside server. 
I've removed libxml2-devel, made server restart, install again 
yum install libxml2-devel
and after that just made 
./configure 
everything is installed and works. So now I'm already learning your examples and tests.
Thank you for your support and for the lib_mysqludf_xml !
Have a nice day !

**Comment by Sarge2013** [comment]
Dear Arnold,

Let me wish YOU, your family and all your close people - The Marry Christmas and Happy New Year !
Wish you stability, prosperity and open new horizons !

Best regards,
Serge

Monday, August 5, 2013, 10:36:19 PM, you wrote:

It's not mine, but also from the repo. It doesn't use libxml2 though.
I'll have to look into it later.

**Comment by hussar** [comment]
Hello,
I've got the same problem on ubuntu server 15.
Installed:
`libxml2-dev`
`libmysqlclient-dev`
After `./configure` command in terminal I got an error: 
`checking for libxml2... configure: error: "could not find headers for libxml2: /include/libxml or /include/libxml2/libxml"`
Could you possibly help me?

**Comment by jasny** [comment]
@hussar Find the `xml2-config` binary (`which xml2-config`) and use it with the `--with-libxml2` option.

**Comment by hussar** [comment]
@jasny in terminal `which xml2-config`
outputs:
`/usr/bin/xml2-config`
in terminal:
`./configure --with-libxml2=/usr/bin/xml2-config`
outputs:
`configure: setting libdir to mysql plugin dir /usr/lib/mysql/plugin
checking for libxml2... configure: error: "could not find libxml2: /usr/bin/xml2-config/lib/libxml2.so"`
How to solve this problem?

**Comment by khazamov** [comment]
hussar, try ./configure --with-libxml2=`locate xml2Conf.sh`

In regards to  jasny's post - what he probably meant is using xml2-config utility in order to find correct include directives and libraries, so you could feed them to configure  via env variables.
 i.e 
:~/xql/lib_mysqludf_xml$ xml2-config --libs --cflags
-lxml2
-I/usr/include/libxml2
:~/xql/lib_mysqludf_xml$ export set CFLAGS="-I/usr/include/libxml2"
:~/xql/lib_mysqludf_xml$ export set LIBS="-lxml2"
:~/xql/lib_mysqludf_xml$ ./configure

should also work.

**Comment by ankitsablok89** [comment]
@khazamov : I have tried doing what you wrote but none of that worked sadly :(

**Comment by khazamov** [comment]
@ankitsablok89, if this is still relevant, can you show us the error message you are getting?

**Comment by bkunal** [comment]
run ./autogen again and they try running ./configure

**Comment by sbenkorichi** [comment]
This might help other users. 
I was stuck trying to install torque, I was getting the same error although, I did install libxml2-devel on centos 7.
The trick I get it working with is with using administration privileges, 
sudo ./configure 
Otherwise, it would result in the same error as reported above.

**Comment by irenge** [comment]
How do one configure this in fedora , I installed lxml2 but still 
``
checking for gzopen in -lz... yes
checking for xmlParseFile in -lxml2... yes
You are trying to use a version 2.* edition of libxml
but an incompatible library. The header files and library seem to be
mismatched. If you have specified LIBXML_INCDIR, make certain to also
specify an appropriate LIBXML_LIBDIR if the libxml2 library is not in the default
directories.
ERROR: configuration failed for package ‘XML’
* removing ‘/home/jules/R/x86_64-redhat-linux-gnu-library/3.4/XML’
Warning in install.packages :
  installation of package ‘XML’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpwrnhm5/downloaded_packages’
``
Any help
